export const stores = [
  {
    id: "1",
    name: "田中ラーメン新宿店",
    address: "東京都新宿区新宿3-1-1",
    category: "ラーメン",
    avgRating: 4.3,
    monthlyCount: 124,
    googleUrl: "https://g.page/tanaka-ramen-shinjuku",
    phone: "03-1234-5678",
    googleConnected: true,
    notifyEmail: "manager@tanaka-ramen.jp",
    notifyThreshold: 3,
  },
  {
    id: "2",
    name: "田中ラーメン渋谷店",
    address: "東京都渋谷区道玄坂2-2-2",
    category: "ラーメン",
    avgRating: 4.1,
    monthlyCount: 98,
    googleUrl: "https://g.page/tanaka-ramen-shibuya",
    phone: "03-2345-6789",
    googleConnected: true,
    notifyEmail: "manager@tanaka-ramen.jp",
    notifyThreshold: 3,
  },
  {
    id: "3",
    name: "佐藤カフェ",
    address: "東京都港区南青山1-1-1",
    category: "カフェ",
    avgRating: 4.5,
    monthlyCount: 156,
    googleUrl: "https://g.page/sato-cafe",
    phone: "03-3456-7890",
    googleConnected: true,
    notifyEmail: "sato@cafe.jp",
    notifyThreshold: 3,
  },
  {
    id: "4",
    name: "山田居酒屋",
    address: "東京都新宿区歌舞伎町1-1-1",
    category: "居酒屋",
    avgRating: 3.9,
    monthlyCount: 87,
    googleUrl: "https://g.page/yamada-izakaya",
    phone: "03-4567-8901",
    googleConnected: false,
    notifyEmail: "yamada@izakaya.jp",
    notifyThreshold: 2,
  },
];

export const kpiData = {
  totalReviews: 1248,
  avgRating: 4.2,
  googleRedirectRate: 78,
  badReviewPreventRate: 92,
};

export const monthlyData = [
  { month: "10月", total: 89, positive: 72, negative: 17 },
  { month: "11月", total: 102, positive: 84, negative: 18 },
  { month: "12月", total: 145, positive: 121, negative: 24 },
  { month: "1月", total: 98, positive: 79, negative: 19 },
  { month: "2月", total: 112, positive: 93, negative: 19 },
  { month: "3月", total: 134, positive: 113, negative: 21 },
  { month: "4月", total: 124, positive: 105, negative: 19 },
];

export const recentReviews = [
  {
    id: "r1",
    store: "佐藤カフェ",
    rating: 5,
    comment: "コーヒーが本当に美味しかったです。また来ます！",
    redirected: true,
    createdAt: "2026-04-20 14:32",
  },
  {
    id: "r2",
    store: "田中ラーメン新宿店",
    rating: 4,
    comment: "スープが濃厚で最高でした。",
    redirected: true,
    createdAt: "2026-04-20 13:15",
  },
  {
    id: "r3",
    store: "山田居酒屋",
    rating: 2,
    comment: "待ち時間が長すぎました。改善してほしいです。",
    redirected: false,
    createdAt: "2026-04-20 12:48",
  },
  {
    id: "r4",
    store: "田中ラーメン渋谷店",
    rating: 5,
    comment: "接客がとても丁寧で感動しました。",
    redirected: true,
    createdAt: "2026-04-20 11:22",
  },
  {
    id: "r5",
    store: "佐藤カフェ",
    rating: 3,
    comment: "席が狭く感じました。料理は美味しかったです。",
    redirected: false,
    createdAt: "2026-04-20 10:05",
  },
  {
    id: "r6",
    store: "田中ラーメン新宿店",
    rating: 4,
    comment: "麺の硬さを選べて良かったです。",
    redirected: true,
    createdAt: "2026-04-20 09:30",
  },
];

export const ratingDistribution = [
  { star: "★5", count: 487, percentage: 39 },
  { star: "★4", count: 374, percentage: 30 },
  { star: "★3", count: 212, percentage: 17 },
  { star: "★2", count: 112, percentage: 9 },
  { star: "★1", count: 63, percentage: 5 },
];

export const allComments = [
  {
    id: "c1",
    store: "佐藤カフェ",
    rating: 5,
    comment: "コーヒーが本当に美味しかったです。スタッフも笑顔で接客してくれて最高でした！",
    redirected: true,
    createdAt: "2026-04-20 14:32",
    category: "接客",
  },
  {
    id: "c2",
    store: "田中ラーメン新宿店",
    rating: 5,
    comment: "スープが濃厚で、チャーシューも柔らかく絶品でした。",
    redirected: true,
    createdAt: "2026-04-20 13:15",
    category: "料理",
  },
  {
    id: "c3",
    store: "山田居酒屋",
    rating: 2,
    comment: "予約していたのに30分以上待たされました。改善してほしいです。",
    redirected: false,
    createdAt: "2026-04-20 12:48",
    category: "待ち時間",
  },
  {
    id: "c4",
    store: "田中ラーメン渋谷店",
    rating: 4,
    comment: "接客がとても丁寧で感動しました。料理も美味しかった。",
    redirected: true,
    createdAt: "2026-04-20 11:22",
    category: "接客",
  },
  {
    id: "c5",
    store: "佐藤カフェ",
    rating: 3,
    comment: "席が少し狭く感じました。コーヒー自体は美味しかったです。",
    redirected: false,
    createdAt: "2026-04-20 10:05",
    category: "環境",
  },
  {
    id: "c6",
    store: "田中ラーメン新宿店",
    rating: 5,
    comment: "麺の硬さを選べて良かったです。また必ず来ます！",
    redirected: true,
    createdAt: "2026-04-20 09:30",
    category: "料理",
  },
  {
    id: "c7",
    store: "山田居酒屋",
    rating: 4,
    comment: "料理が美味しかった。お酒の種類も豊富で満足です。",
    redirected: true,
    createdAt: "2026-04-19 20:15",
    category: "料理",
  },
  {
    id: "c8",
    store: "佐藤カフェ",
    rating: 1,
    comment: "注文から40分待ちましたが、まだ来ませんでした。途中で帰りました。",
    redirected: false,
    createdAt: "2026-04-19 15:30",
    category: "待ち時間",
  },
  {
    id: "c9",
    store: "田中ラーメン渋谷店",
    rating: 5,
    comment: "定番のしょうゆラーメンが最高です。毎週通いたい。",
    redirected: true,
    createdAt: "2026-04-19 12:00",
    category: "料理",
  },
  {
    id: "c10",
    store: "山田居酒屋",
    rating: 3,
    comment: "雰囲気は良いですが、少し値段が高いと感じました。",
    redirected: false,
    createdAt: "2026-04-18 21:00",
    category: "価格",
  },
];

export const trendData = [
  { date: "4/14", avg: 4.0 },
  { date: "4/15", avg: 4.2 },
  { date: "4/16", avg: 4.1 },
  { date: "4/17", avg: 4.4 },
  { date: "4/18", avg: 4.3 },
  { date: "4/19", avg: 4.2 },
  { date: "4/20", avg: 4.3 },
];
